### PR TITLE
Add Tedium.co

### PR DESCRIPTION
**Pull request by readtedium**
Tedium straddles the line between newsletter and blog, so hopefully you’ll take us. :)

### CODE REVIEW

**Comment by m8** [comment]
thanks for the contribution but i think doesn't fit the format of the project.

**Comment by readtedium** [comment]
Are you sure? I have written about the specific topic of bringing back independent blogging many times and self-host everything for this reason.

See: https://tedium.co/2019/01/01/2019-independent-blogging-trends/

I should also point out that I have had more than a dozen HN posts get above 100 points over the past five years. https://hn.algolia.com/?q=tedium.co

**Comment by enkiv2** [comment]
Tedium has a lot of technical content (more on average than many of the blogs already featured), so it seems like it ought to be a good fit.

**Comment by m8** [comment]
I'm apologize for any inconvenience caused. I was a little tired today :/ I thought it's more about news (you wrote it's like a newspaper style) . Thanks for the contribution.

**Comment by readtedium** [comment]
Thank you for hearing me out, I appreciate it.

**Comment by m8** [comment]
I can't thank you enough. I'm having fun in the retro mood right now!

**Pull request merged**
